# Generated by Django 6.0.2 on 2026-04-12 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='broker_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
