# Generated by Django 6.0.2 on 2026-04-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_message_sender__a3289a_idx_api_message_sender__54a403_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_sender__54a403_idx',
            old_name='api_message_sender__a3289a_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_receive_efffdf_idx',
            old_name='api_message_recipie_eb753b_idx',
        ),
    ]
