# Generated by Django 6.0.2 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_api_message_sender__a3289a_idx_api_message_sender__54a403_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdetail',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='building_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='door_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='floor_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='window_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='window_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
