# Generated by Django 6.0.2 on 2026-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_listingdetail_balcony_listingdetail_building_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdetail',
            name='deposit_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Барьцаа сарын тоо', null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Тавилгагүй (Хоосон)'), ('semi_furnished', 'Хагас тавилгатай'), ('fully_furnished', 'Бүрэн тавилгатай')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='payment_condition',
            field=models.CharField(blank=True, choices=[('1_plus_1', '1+1 (1 сар урьдчилгаа, 1 сар барьцаа)'), ('3_plus_1', '3+1 (3 сар урьдчилгаа, 1 сар барьцаа)'), ('6_plus_1', '6+1 (6 сар урьдчилгаа, 1 сар барьцаа)'), ('monthly', 'Сар бүр (Барьцаатай)'), ('no_deposit', 'Барьцаагүй'), ('custom', 'Бусад (Тохиролцоно)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='upfront_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Урьдчилж төлөх сарын тоо', null=True),
        ),
    ]
